# Generated by Django 4.2.4 on 2023-10-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Coding Assessment', 'Coding Assessment'), ('Interview', 'Interview'), ('Offer Receieved', 'Offer Receieved'), ('Rejected', 'Rejected'), ('Ghosted', 'Ghosted')], max_length=50),
        ),
    ]
