# Generated by Django 4.2.6 on 2023-11-01 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='Intern at FIU', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
