# Generated by Django 4.2.6 on 2023-11-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_job_job_name_alter_job_date_posted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
