# Generated by Django 4.2.7 on 2023-11-22 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_internship_city_internship_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quickstart.applicant')),
                ('Name', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=12)),
                ('degree', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_applicants',
            field=models.ManyToManyField(to='quickstart.applicant'),
        ),
    ]
