# Generated by Django 4.2.7 on 2023-11-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_resume_job_job_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.TextField(default='TBD'),
            preserve_default=False,
        ),
    ]
