# Generated by Django 4.2.7 on 2023-11-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_resume_name_remove_resume_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_id',
            field=models.AutoField(default='123', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quickstart.applicant'),
        ),
    ]
