# Generated by Django 4.2.7 on 2023-11-29 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_resume_resume_id_alter_resume_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='internship_applicants',
            field=models.ManyToManyField(blank=True, null=True, to='quickstart.applicant'),
        ),
        migrations.AlterField(
            model_name='applicantinternship',
            name='date_applied',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='applicantjob',
            name='date_applied',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_applicants',
            field=models.ManyToManyField(blank=True, null=True, to='quickstart.applicant'),
        ),
    ]
